repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: genombatchqc
  description: QC plant long-reads assembled genomes with selectable modules
  author: Yangzi wangyz.benniao@gmail.com
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
